# Generated by Django 5.1.6 on 2026-07-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyId', models.IntegerField()),
                ('PolicyNumber', models.CharField(max_length=100)),
                ('PolicyHolderName', models.CharField(max_length=100)),
                ('PolicyType', models.CharField(max_length=100)),
                ('PremiumAmount', models.IntegerField()),
                ('CoverageAmount', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
