# Generated by Django 5.1.6 on 2026-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('upi_id', models.IntegerField()),
                ('money', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('paid_to', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
    ]
