# Generated by Django 5.1.6 on 2026-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('quntity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('foodistem', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('paymentmode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FDA',
            },
        ),
    ]
