# Generated by Django 5.1.6 on 2026-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('run', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
