# Generated by Django 5.1.6 on 2026-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterField(
            model_name='team',
            name='no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='run',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
    ]
